USE food_delivery_portfolio;

-- =====================================================
-- EXPLORATORY DATA ANALYSIS (EDA)
-- Project: Food Delivery Analytics SQL Project
-- Description: Initial business overview and key metrics
-- =====================================================


-- =====================================================
-- DATASET OVERVIEW
-- =====================================================

-- Total number of orders
SELECT COUNT(*) AS total_orders
FROM orders_data;

-- Total number of unique customers
SELECT COUNT(DISTINCT customer_id) AS unique_customers
FROM orders_data;

-- Total number of unique restaurants
SELECT COUNT(DISTINCT restaurant_name) AS unique_restaurants
FROM orders_data;

-- Total number of cities covered
SELECT COUNT(DISTINCT city) AS unique_cities
FROM orders_data;


-- =====================================================
-- REVENUE ANALYSIS
-- =====================================================

-- Total revenue generated from all orders
SELECT ROUND(SUM(order_value), 2) AS total_revenue
FROM orders_data;

-- Average order value
SELECT ROUND(AVG(order_value), 2) AS average_order_value
FROM orders_data;


-- =====================================================
-- GEOGRAPHIC PERFORMANCE
-- =====================================================

-- Revenue generated by each city
SELECT
    city,
    ROUND(SUM(order_value), 2) AS total_revenue
FROM orders_data
GROUP BY city
ORDER BY total_revenue DESC;


-- =====================================================
-- CUISINE PERFORMANCE
-- =====================================================

-- Revenue generated by each cuisine category
SELECT
    cuisine,
    ROUND(SUM(order_value), 2) AS total_revenue
FROM orders_data
GROUP BY cuisine
ORDER BY total_revenue DESC;


-- =====================================================
-- PAYMENT METHOD ANALYSIS
-- =====================================================

-- Number of orders by payment method
SELECT
    payment_method,
    COUNT(*) AS total_orders
FROM orders_data
GROUP BY payment_method
ORDER BY total_orders DESC;


-- =====================================================
-- DELIVERY STATUS ANALYSIS
-- =====================================================

-- Number of orders by delivery status
SELECT
    delivery_status,
    COUNT(*) AS total_orders
FROM orders_data
GROUP BY delivery_status
ORDER BY total_orders DESC;

-- Revenue Performance by City
SELECT
    city,
    COUNT(*) AS total_orders,
    ROUND(SUM(order_value), 2) AS total_revenue,
    ROUND(AVG(order_value), 2) AS average_order_value
FROM orders_data
GROUP BY city
ORDER BY total_revenue DESC;